version: 1.2
workflows:
  - name: sQTLAnalysis
    subclass: WDL
    primaryDescriptorPath: /sqtl/sQTL.wdl
  - name: CrossCheckSample
    subclass: WDL
    primaryDescriptorPath: /utils/Fingerprinting.wdl
  - name: ConvertPlinkToVcf
    subclass: WDL
    primaryDescriptorPath: /utils/Plink.wdl
